### ISSUE TITLE
Fail to download shell script in raw.githubcontent websites in China

### ISSUE THREAD

**Issue by gavinisagi** [Daemon-Technologies/docs#5]
### Description

```
$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.0/install.sh | bash
```

Shows 

```
Failed to connect raw.githubusercontent.com (port 443) connection refused
```

Because of the DNS pollution protection, websites above cannot be fetched by users in China.

**Comment by whoabuddy** [comment]
I had an idea - could you fork this repo and set up github pages on an actual domain (instead of github.io)? Then you would have an easy way to distribute the shell file and/or update the contents on a new release.

**Comment by gavinisagi** [comment]
https://github.com/Daemon-Technologies/docs/pull/36
